spring:
  application:
    name: omega-gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos-password

framework:
  gateway:
    token-secret: omega-authorization-jwt-secret-random
    allow-list:
      - method: POST
        path: /omega-authorization-service/authorization/login
      - path: /omega-admin-service/**
      - path: /omega-file-service/**

knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      enabled: true
      version: openapi3
